/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IRiskScorerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateRiskScore"
      | "updateRiskParameters"
      | "validateScore"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateRiskScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRiskParameters",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateScore",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRiskParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateScore",
    data: BytesLike
  ): Result;
}

export interface IRiskScorer extends BaseContract {
  connect(runner?: ContractRunner | null): IRiskScorer;
  waitForDeployment(): Promise<this>;

  interface: IRiskScorerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateRiskScore: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { score: bigint; tier: bigint }],
    "view"
  >;

  updateRiskParameters: TypedContractMethod<
    [params: BytesLike],
    [void],
    "nonpayable"
  >;

  validateScore: TypedContractMethod<
    [user: AddressLike, minScore: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateRiskScore"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { score: bigint; tier: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateRiskParameters"
  ): TypedContractMethod<[params: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validateScore"
  ): TypedContractMethod<
    [user: AddressLike, minScore: BigNumberish],
    [boolean],
    "view"
  >;

  filters: {};
}
