/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRiskScorer__factory } from "./IRiskScorer__factory";
export { OCCRScorer__factory } from "./OCCRScorer__factory";
